### ISSUE TITLE
cannot list me server on the kaillera master

### ISSUE THREAD

**Issue by xqgg** [God-Weapon/EmuLinkerSF#7]
My server cannot be exposed to kaillera

**Comment by xqgg** [comment]
You can connect to my server by entering the ip address, but it won't show up on the list

**Comment by xqgg** [comment]
![1](https://user-images.githubusercontent.com/50631866/223146150-78f92d91-2bfe-4550-bbda-3a9df8d3d025.png)
![2](https://user-images.githubusercontent.com/50631866/223146484-12aa6cdb-d9de-4195-9777-0f6bb43e9e7f.png)

**Comment by kaillerareborn** [comment]
This isn't server's fault, but rather the official list (it doesn't show the full list of servers for now). You can use a client that uses the alternative Servers List in the meantime until it's fixed.
