### ISSUE TITLE
Whether GBA games are planned to support online

### ISSUE THREAD

**Issue by hildoszlengq** [God-Weapon/EmuLinkerSF#9]

**Comment by hildoszlengq** [comment]
I think kaillera support for GBA games will increase the number of kaillera users. Currently GBA games do not have a good remote online

**Comment by hildoszlengq** [comment]
Hope to actively co-develop with them to make Kaillera support GBA games remote online

**Comment by hildoszlengq** [comment]
I think kaillera support for GBA games will increase the number of kaillera users. Currently GBA games do not have a good remote online

**Comment by hildoszlengq** [comment]
VBA-M or mGBA Emulator Hope to actively co-develop with them to make Kaillera support GBA games remote online

**Comment by Jgunishka** [comment]
Not planned, but you can try RetroArch with kaillera netplay, it supports many different emulator cores including GBA (although not all cores may be fully functional via kaillera). For more info visit: https://kaillerareborn.github.io
